#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["fonttools==4.60.0"]
# ///
"""Rebuild the download badges: uv run art/badges/generate.py (requires rsvg-convert)."""

from copy import deepcopy
from html import escape
from pathlib import Path
import shutil
import subprocess
import xml.etree.ElementTree as ET

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


HERE = Path(__file__).resolve().parent
FONT = HERE.parents[1] / "shared/src/commonMain/composeResources/font/Lexend_variable.ttf"
SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)
ET.register_namespace("xlink", "http://www.w3.org/1999/xlink")

# Every badge uses these exact dimensions, plate, text baselines and icon slot.
# 480 × 144 is 3× a 160 × 48 display, covering the README/release widths of 140/150.
WIDTH, HEIGHT = 480, 144
PLATE = '<rect x="0.5" y="0.5" width="239" height="71" rx="8" fill="#080808" stroke="#91959C"/>'
BADGES = (
    ("get-it-on-github", "github", "GET IT ON", "GitHub", "Get it on GitHub"),
    ("IzzyOnDroid", "izzyondroid", "GET IT ON", "IzzyOnDroid", "Get it on IzzyOnDroid"),
    ("google-play", "google-play", "GET IT ON", "Google Play", "Get it on Google Play"),
    ("app-store", "apple", "DOWNLOAD ON THE", "App Store", "Download on the App Store"),
    ("AltSource_Blue", "altsource", "ADD", "AltSource", "Add the AltStore source"),
    ("Download_Blue", "ipa", "DOWNLOAD", "IPA file", "Download the IPA file"),
)


def number(value):
    return f"{value:.3f}".rstrip("0").rstrip(".") or "0"


def outlined_text(font, text, size, x, baseline, spacing=0):
    """Outline the bundled font so SVG viewers cannot substitute another font."""
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / font["head"].unitsPerEm
    pen = SVGPathPen(glyphs, ntos=number)
    cursor = x
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, cursor, baseline)))
        cursor += glyph.width * scale + spacing
    # Use the ink edge, rather than the font's side bearing, as the shared left edge.
    bounds = BoundsPen(glyphs)
    glyphs[cmap[ord(text[0])]].draw(bounds)
    bearing = bounds.bounds[0] * scale
    assert cursor - spacing - bearing <= 226, f"Label exceeds right inset: {text}"
    return f'<path transform="translate({number(-bearing)} 0)" d="{pen.getCommands()}"/>'


def icon_markup(name):
    mark = ET.parse(HERE / "marks" / f"{name}.svg").getroot()
    # The source viewBoxes tightly frame each mark. All fit the same 40 × 40 slot.
    mark.attrib.update(x="14", y="16", width="40", height="40", preserveAspectRatio="xMidYMid meet")
    return ET.tostring(mark, encoding="unicode")


def main():
    renderer = shutil.which("rsvg-convert")
    if renderer is None:
        raise SystemExit("Install librsvg (rsvg-convert) to export the PNGs.")
    source = TTFont(FONT)
    header_font = instantiateVariableFont(deepcopy(source), {"wght": 400})
    title_font = instantiateVariableFont(deepcopy(source), {"wght": 450})
    for filename, mark, header, title, label in BADGES:
        header_path = outlined_text(header_font, header, 9, 68, 25, spacing=0.5)
        title_path = outlined_text(title_font, title, 22, 68, 51)
        svg = (
            f'<svg xmlns="{SVG_NS}" width="{WIDTH}" height="{HEIGHT}" '
            'viewBox="0 0 240 72" role="img" aria-labelledby="badge-title">\n'
            f'  <title id="badge-title">{escape(label)}</title>\n'
            '  <!-- Generated by generate.py; edit the shared layout or marks, then rebuild. -->\n'
            f'  {PLATE}\n'
            f'  {icon_markup(mark)}\n'
            f'  <g fill="#FFFFFF">{header_path}{title_path}</g>\n'
            '</svg>\n'
        )
        svg_path = HERE / f"{filename}.svg"
        png_path = HERE / f"{filename}.png"
        svg_path.write_text(svg)
        subprocess.run(
            [renderer, "--width", str(WIDTH), "--height", str(HEIGHT),
             "--output", str(png_path), str(svg_path)], check=True,
        )
        print(f"{filename}: {WIDTH} × {HEIGHT}, PNG {png_path.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
